//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ejemplo_C_sharp.Timbrado_Retenciones_Pruebas {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:WashOut", ConfigurationName="Timbrado_Retenciones_Pruebas.retencion_port")]
    public interface retencion_port {
        
        [System.ServiceModel.OperationContractAttribute(Action="timbrar_retencion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="timbrar_retencion_result")]
        Ejemplo_C_sharp.Timbrado_Retenciones_Pruebas.timbrar_retencion_result timbrar_retencion(string username, string password, string sxml);
        
        [System.ServiceModel.OperationContractAttribute(Action="timbrar_retencion", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="timbrar_retencion_result")]
        System.Threading.Tasks.Task<Ejemplo_C_sharp.Timbrado_Retenciones_Pruebas.timbrar_retencion_result> timbrar_retencionAsync(string username, string password, string sxml);
        
        [System.ServiceModel.OperationContractAttribute(Action="cancelar_retencion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="cancelar_retencion_result")]
        Ejemplo_C_sharp.Timbrado_Retenciones_Pruebas.cancelar_retencion_result cancelar_retencion(string username, string password, string rfcemisor, Ejemplo_C_sharp.Timbrado_Retenciones_Pruebas.uuid uuids, string cert_pem, string llave_pem);
        
        [System.ServiceModel.OperationContractAttribute(Action="cancelar_retencion", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="cancelar_retencion_result")]
        System.Threading.Tasks.Task<Ejemplo_C_sharp.Timbrado_Retenciones_Pruebas.cancelar_retencion_result> cancelar_retencionAsync(string username, string password, string rfcemisor, Ejemplo_C_sharp.Timbrado_Retenciones_Pruebas.uuid uuids, string cert_pem, string llave_pem);
        
        [System.ServiceModel.OperationContractAttribute(Action="cancelar_masivo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="cancelar_masivo_result")]
        Ejemplo_C_sharp.Timbrado_Retenciones_Pruebas.cancelar_masivo_result cancelar_masivo(string username, string password, string rfcemisor, Ejemplo_C_sharp.Timbrado_Retenciones_Pruebas.uuid uuids, string cert_pem, string llave_pem);
        
        [System.ServiceModel.OperationContractAttribute(Action="cancelar_masivo", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="cancelar_masivo_result")]
        System.Threading.Tasks.Task<Ejemplo_C_sharp.Timbrado_Retenciones_Pruebas.cancelar_masivo_result> cancelar_masivoAsync(string username, string password, string rfcemisor, Ejemplo_C_sharp.Timbrado_Retenciones_Pruebas.uuid uuids, string cert_pem, string llave_pem);
        
        [System.ServiceModel.OperationContractAttribute(Action="consulta_acuse_cancelacion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="consulta_acuse_cancelacion_result")]
        Ejemplo_C_sharp.Timbrado_Retenciones_Pruebas.consulta_acuse_cancelacion_result consulta_acuse_cancelacion(string username, string password, string folioSeguimiento);
        
        [System.ServiceModel.OperationContractAttribute(Action="consulta_acuse_cancelacion", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="consulta_acuse_cancelacion_result")]
        System.Threading.Tasks.Task<Ejemplo_C_sharp.Timbrado_Retenciones_Pruebas.consulta_acuse_cancelacion_result> consulta_acuse_cancelacionAsync(string username, string password, string folioSeguimiento);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:WashOut")]
    public partial class timbrar_retencion_result : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string xmlField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string xml {
            get {
                return this.xmlField;
            }
            set {
                this.xmlField = value;
                this.RaisePropertyChanged("xml");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:WashOut")]
    public partial class consulta_acuse_cancelacion_result : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string acuse_cancelacionField;
        
        private string comprobantes_canceladosField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string acuse_cancelacion {
            get {
                return this.acuse_cancelacionField;
            }
            set {
                this.acuse_cancelacionField = value;
                this.RaisePropertyChanged("acuse_cancelacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string comprobantes_cancelados {
            get {
                return this.comprobantes_canceladosField;
            }
            set {
                this.comprobantes_canceladosField = value;
                this.RaisePropertyChanged("comprobantes_cancelados");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:WashOut")]
    public partial class cancelar_masivo_result : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string acuse_cancelacionField;
        
        private string folio_seguimientoField;
        
        private string estatus_cancelacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string acuse_cancelacion {
            get {
                return this.acuse_cancelacionField;
            }
            set {
                this.acuse_cancelacionField = value;
                this.RaisePropertyChanged("acuse_cancelacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string folio_seguimiento {
            get {
                return this.folio_seguimientoField;
            }
            set {
                this.folio_seguimientoField = value;
                this.RaisePropertyChanged("folio_seguimiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string estatus_cancelacion {
            get {
                return this.estatus_cancelacionField;
            }
            set {
                this.estatus_cancelacionField = value;
                this.RaisePropertyChanged("estatus_cancelacion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:WashOut")]
    public partial class cancelar_retencion_result : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string acuse_cancelacionField;
        
        private string comprobantes_canceladosField;
        
        private string estatus_cancelacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string acuse_cancelacion {
            get {
                return this.acuse_cancelacionField;
            }
            set {
                this.acuse_cancelacionField = value;
                this.RaisePropertyChanged("acuse_cancelacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string comprobantes_cancelados {
            get {
                return this.comprobantes_canceladosField;
            }
            set {
                this.comprobantes_canceladosField = value;
                this.RaisePropertyChanged("comprobantes_cancelados");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string estatus_cancelacion {
            get {
                return this.estatus_cancelacionField;
            }
            set {
                this.estatus_cancelacionField = value;
                this.RaisePropertyChanged("estatus_cancelacion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:WashOut")]
    public partial class Uuid : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string uuidField;
        
        private string motivoField;
        
        private string folio_sustitutoField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string uuid {
            get {
                return this.uuidField;
            }
            set {
                this.uuidField = value;
                this.RaisePropertyChanged("uuid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string motivo {
            get {
                return this.motivoField;
            }
            set {
                this.motivoField = value;
                this.RaisePropertyChanged("motivo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string folio_sustituto {
            get {
                return this.folio_sustitutoField;
            }
            set {
                this.folio_sustitutoField = value;
                this.RaisePropertyChanged("folio_sustituto");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:WashOut")]
    public partial class uuid : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Uuid[] uuidField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public Uuid[] Uuid {
            get {
                return this.uuidField;
            }
            set {
                this.uuidField = value;
                this.RaisePropertyChanged("Uuid");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface retencion_portChannel : Ejemplo_C_sharp.Timbrado_Retenciones_Pruebas.retencion_port, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class retencion_portClient : System.ServiceModel.ClientBase<Ejemplo_C_sharp.Timbrado_Retenciones_Pruebas.retencion_port>, Ejemplo_C_sharp.Timbrado_Retenciones_Pruebas.retencion_port {
        
        public retencion_portClient() {
        }
        
        public retencion_portClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public retencion_portClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public retencion_portClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public retencion_portClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Ejemplo_C_sharp.Timbrado_Retenciones_Pruebas.timbrar_retencion_result timbrar_retencion(string username, string password, string sxml) {
            return base.Channel.timbrar_retencion(username, password, sxml);
        }
        
        public System.Threading.Tasks.Task<Ejemplo_C_sharp.Timbrado_Retenciones_Pruebas.timbrar_retencion_result> timbrar_retencionAsync(string username, string password, string sxml) {
            return base.Channel.timbrar_retencionAsync(username, password, sxml);
        }
        
        public Ejemplo_C_sharp.Timbrado_Retenciones_Pruebas.cancelar_retencion_result cancelar_retencion(string username, string password, string rfcemisor, Ejemplo_C_sharp.Timbrado_Retenciones_Pruebas.uuid uuids, string cert_pem, string llave_pem) {
            return base.Channel.cancelar_retencion(username, password, rfcemisor, uuids, cert_pem, llave_pem);
        }
        
        public System.Threading.Tasks.Task<Ejemplo_C_sharp.Timbrado_Retenciones_Pruebas.cancelar_retencion_result> cancelar_retencionAsync(string username, string password, string rfcemisor, Ejemplo_C_sharp.Timbrado_Retenciones_Pruebas.uuid uuids, string cert_pem, string llave_pem) {
            return base.Channel.cancelar_retencionAsync(username, password, rfcemisor, uuids, cert_pem, llave_pem);
        }
        
        public Ejemplo_C_sharp.Timbrado_Retenciones_Pruebas.cancelar_masivo_result cancelar_masivo(string username, string password, string rfcemisor, Ejemplo_C_sharp.Timbrado_Retenciones_Pruebas.uuid uuids, string cert_pem, string llave_pem) {
            return base.Channel.cancelar_masivo(username, password, rfcemisor, uuids, cert_pem, llave_pem);
        }
        
        public System.Threading.Tasks.Task<Ejemplo_C_sharp.Timbrado_Retenciones_Pruebas.cancelar_masivo_result> cancelar_masivoAsync(string username, string password, string rfcemisor, Ejemplo_C_sharp.Timbrado_Retenciones_Pruebas.uuid uuids, string cert_pem, string llave_pem) {
            return base.Channel.cancelar_masivoAsync(username, password, rfcemisor, uuids, cert_pem, llave_pem);
        }
        
        public Ejemplo_C_sharp.Timbrado_Retenciones_Pruebas.consulta_acuse_cancelacion_result consulta_acuse_cancelacion(string username, string password, string folioSeguimiento) {
            return base.Channel.consulta_acuse_cancelacion(username, password, folioSeguimiento);
        }
        
        public System.Threading.Tasks.Task<Ejemplo_C_sharp.Timbrado_Retenciones_Pruebas.consulta_acuse_cancelacion_result> consulta_acuse_cancelacionAsync(string username, string password, string folioSeguimiento) {
            return base.Channel.consulta_acuse_cancelacionAsync(username, password, folioSeguimiento);
        }
    }
}
