//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Main.TimboxWSValidador {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:WashOut", ConfigurationName="TimboxWSValidador.valida_cfdi_port")]
    public interface valida_cfdi_port {
        
        [System.ServiceModel.OperationContractAttribute(Action="validar_cfdi", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="validar_cfdi_result")]
        Main.TimboxWSValidador.validar_cfdi_result validar_cfdi(string username, string password, Main.TimboxWSValidador.comprobante validar);
        
        [System.ServiceModel.OperationContractAttribute(Action="validar_cfdi", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="validar_cfdi_result")]
        System.Threading.Tasks.Task<Main.TimboxWSValidador.validar_cfdi_result> validar_cfdiAsync(string username, string password, Main.TimboxWSValidador.comprobante validar);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:WashOut")]
    public partial class comprobante : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Comprobante[] comprobanteField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public Comprobante[] Comprobante {
            get {
                return this.comprobanteField;
            }
            set {
                this.comprobanteField = value;
                this.RaisePropertyChanged("Comprobante");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:WashOut")]
    public partial class Comprobante : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string external_idField;
        
        private string sxmlField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string external_id {
            get {
                return this.external_idField;
            }
            set {
                this.external_idField = value;
                this.RaisePropertyChanged("external_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string sxml {
            get {
                return this.sxmlField;
            }
            set {
                this.sxmlField = value;
                this.RaisePropertyChanged("sxml");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:WashOut")]
    public partial class validar_cfdi_result : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string resultadosField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string resultados {
            get {
                return this.resultadosField;
            }
            set {
                this.resultadosField = value;
                this.RaisePropertyChanged("resultados");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface valida_cfdi_portChannel : Main.TimboxWSValidador.valida_cfdi_port, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class valida_cfdi_portClient : System.ServiceModel.ClientBase<Main.TimboxWSValidador.valida_cfdi_port>, Main.TimboxWSValidador.valida_cfdi_port {
        
        public valida_cfdi_portClient() {
        }
        
        public valida_cfdi_portClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public valida_cfdi_portClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public valida_cfdi_portClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public valida_cfdi_portClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Main.TimboxWSValidador.validar_cfdi_result validar_cfdi(string username, string password, Main.TimboxWSValidador.comprobante validar) {
            return base.Channel.validar_cfdi(username, password, validar);
        }
        
        public System.Threading.Tasks.Task<Main.TimboxWSValidador.validar_cfdi_result> validar_cfdiAsync(string username, string password, Main.TimboxWSValidador.comprobante validar) {
            return base.Channel.validar_cfdiAsync(username, password, validar);
        }
    }
}
