//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Main.TimboxWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:WashOut", ConfigurationName="TimboxWS.timbrado_cfdi33_port")]
    public interface timbrado_cfdi33_port {
        
        [System.ServiceModel.OperationContractAttribute(Action="timbrar_cfdi", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="timbrar_cfdi_result")]
        Main.TimboxWS.timbrar_cfdi_result timbrar_cfdi(string username, string password, string sxml);
        
        [System.ServiceModel.OperationContractAttribute(Action="timbrar_cfdi", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="timbrar_cfdi_result")]
        System.Threading.Tasks.Task<Main.TimboxWS.timbrar_cfdi_result> timbrar_cfdiAsync(string username, string password, string sxml);
        
        [System.ServiceModel.OperationContractAttribute(Action="cancelar_cfdi", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="cancelar_cfdi_result")]
        Main.TimboxWS.cancelar_cfdi_result cancelar_cfdi(string username, string password, string rfcemisor, Main.TimboxWS.uuid uuids, string pfxbase64, string pfxpassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="cancelar_cfdi", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="cancelar_cfdi_result")]
        System.Threading.Tasks.Task<Main.TimboxWS.cancelar_cfdi_result> cancelar_cfdiAsync(string username, string password, string rfcemisor, Main.TimboxWS.uuid uuids, string pfxbase64, string pfxpassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="cancelar_cfdi_certs", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="cancelar_cfdi_certs_result")]
        Main.TimboxWS.cancelar_cfdi_certs_result cancelar_cfdi_certs(string username, string password, string rfcemisor, Main.TimboxWS.uuid uuids, string cert_pem, string llave_pem, string llave_password);
        
        [System.ServiceModel.OperationContractAttribute(Action="cancelar_cfdi_certs", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="cancelar_cfdi_certs_result")]
        System.Threading.Tasks.Task<Main.TimboxWS.cancelar_cfdi_certs_result> cancelar_cfdi_certsAsync(string username, string password, string rfcemisor, Main.TimboxWS.uuid uuids, string cert_pem, string llave_pem, string llave_password);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2114.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:WashOut")]
    public partial class timbrar_cfdi_result : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string xmlField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string xml {
            get {
                return this.xmlField;
            }
            set {
                this.xmlField = value;
                this.RaisePropertyChanged("xml");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2114.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:WashOut")]
    public partial class cancelar_cfdi_certs_result : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string acuse_cancelacionField;
        
        private string comprobantes_canceladosField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string acuse_cancelacion {
            get {
                return this.acuse_cancelacionField;
            }
            set {
                this.acuse_cancelacionField = value;
                this.RaisePropertyChanged("acuse_cancelacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string comprobantes_cancelados {
            get {
                return this.comprobantes_canceladosField;
            }
            set {
                this.comprobantes_canceladosField = value;
                this.RaisePropertyChanged("comprobantes_cancelados");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2114.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:WashOut")]
    public partial class cancelar_cfdi_result : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string acuse_cancelacionField;
        
        private string comprobantes_canceladosField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string acuse_cancelacion {
            get {
                return this.acuse_cancelacionField;
            }
            set {
                this.acuse_cancelacionField = value;
                this.RaisePropertyChanged("acuse_cancelacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string comprobantes_cancelados {
            get {
                return this.comprobantes_canceladosField;
            }
            set {
                this.comprobantes_canceladosField = value;
                this.RaisePropertyChanged("comprobantes_cancelados");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2114.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:WashOut")]
    public partial class uuid : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] uuid1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute("uuid", IsNullable=true)]
        public string[] uuid1 {
            get {
                return this.uuid1Field;
            }
            set {
                this.uuid1Field = value;
                this.RaisePropertyChanged("uuid1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface timbrado_cfdi33_portChannel : Main.TimboxWS.timbrado_cfdi33_port, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class timbrado_cfdi33_portClient : System.ServiceModel.ClientBase<Main.TimboxWS.timbrado_cfdi33_port>, Main.TimboxWS.timbrado_cfdi33_port {
        
        public timbrado_cfdi33_portClient() {
        }
        
        public timbrado_cfdi33_portClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public timbrado_cfdi33_portClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public timbrado_cfdi33_portClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public timbrado_cfdi33_portClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Main.TimboxWS.timbrar_cfdi_result timbrar_cfdi(string username, string password, string sxml) {
            return base.Channel.timbrar_cfdi(username, password, sxml);
        }
        
        public System.Threading.Tasks.Task<Main.TimboxWS.timbrar_cfdi_result> timbrar_cfdiAsync(string username, string password, string sxml) {
            return base.Channel.timbrar_cfdiAsync(username, password, sxml);
        }
        
        public Main.TimboxWS.cancelar_cfdi_result cancelar_cfdi(string username, string password, string rfcemisor, Main.TimboxWS.uuid uuids, string pfxbase64, string pfxpassword) {
            return base.Channel.cancelar_cfdi(username, password, rfcemisor, uuids, pfxbase64, pfxpassword);
        }
        
        public System.Threading.Tasks.Task<Main.TimboxWS.cancelar_cfdi_result> cancelar_cfdiAsync(string username, string password, string rfcemisor, Main.TimboxWS.uuid uuids, string pfxbase64, string pfxpassword) {
            return base.Channel.cancelar_cfdiAsync(username, password, rfcemisor, uuids, pfxbase64, pfxpassword);
        }
        
        public Main.TimboxWS.cancelar_cfdi_certs_result cancelar_cfdi_certs(string username, string password, string rfcemisor, Main.TimboxWS.uuid uuids, string cert_pem, string llave_pem, string llave_password) {
            return base.Channel.cancelar_cfdi_certs(username, password, rfcemisor, uuids, cert_pem, llave_pem, llave_password);
        }
        
        public System.Threading.Tasks.Task<Main.TimboxWS.cancelar_cfdi_certs_result> cancelar_cfdi_certsAsync(string username, string password, string rfcemisor, Main.TimboxWS.uuid uuids, string cert_pem, string llave_pem, string llave_password) {
            return base.Channel.cancelar_cfdi_certsAsync(username, password, rfcemisor, uuids, cert_pem, llave_pem, llave_password);
        }
    }
}
